[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20180529.0.0"

[prune]
  go-tests = true
  unused-packages = true
